function DphiDx = WENO5(phi,i,hx,a)
if a>0
    DphiDx = (1/(12*hx))*(phi(i-2)-8*phi(i-1)+8*phi(i+1)-phi(i+2))...
        -psiWENO((phi(i-1)-2*phi(i-2)+phi(i-3))/hx,...
        (phi(i)-2*phi(i-1)+phi(i-2))/hx,...
        (phi(i+1)-2*phi(i)+phi(i-1))/hx,...
        (phi(i+2)-2*phi(i+1)+phi(i))/hx);
elseif a<0
    DphiDx = (1/(12*hx))*(phi(i-2)-8*phi(i-1)+8*phi(i+1)-phi(i+2))...
        +psiWENO((phi(i+3)-2*phi(i+2)+phi(i+1))/hx,...
        (phi(i+2)-2*phi(i+1)+phi(i))/hx,...
        (phi(i+1)-2*phi(i)+phi(i-1))/hx,...
        (phi(i)-2*phi(i-1)+phi(i-2))/hx);
end
end