function [DphiDx,DphiDy,uCell,vCell] = WENO5_2D(phi,u,v,M,N)
global hx;
global hy;

uCell=zeros(M+6,N+6);
vCell=zeros(M+6,N+6);
DphiDx=zeros(M+6,N+6);
DphiDy=zeros(M+6,N+6);

for i=4:M+3
    for j=4:N+3
        uCell(i,j)=(u(i-3,j-2)+u(i-2,j-2))/2; % Values of u,v at cell centers
        vCell(i,j)=(v(i-2,j-3)+v(i-2,j-2))/2;
    end
end
for i=4:M+3
    for j=4:N+3
        if uCell(i,j)>=0
            DphiDx(i,j) = (1/(12*hx))*(phi(i-2,j)-8*phi(i-1,j)+8*phi(i+1,j)-phi(i+2,j))...
                -psiWENO((phi(i-1,j)-2*phi(i-2,j)+phi(i-3,j))/hx,...
                (phi(i,j)-2*phi(i-1,j)+phi(i-2,j))/hx,...
                (phi(i+1,j)-2*phi(i,j)+phi(i-1,j))/hx,...
                (phi(i+2,j)-2*phi(i+1,j)+phi(i,j))/hx);
        elseif uCell(i,j)<0
            DphiDx(i,j) = (1/(12*hx))*(phi(i-2,j)-8*phi(i-1,j)+8*phi(i+1,j)-phi(i+2,j))...
                +psiWENO((phi(i+3,j)-2*phi(i+2,j)+phi(i+1,j))/hx,...
                (phi(i+2,j)-2*phi(i+1,j)+phi(i,j))/hx,...
                (phi(i+1,j)-2*phi(i,j)+phi(i-1,j))/hx,...
                (phi(i,j)-2*phi(i-1,j)+phi(i-2,j))/hx);
        end
        if vCell(i,j)>=0
            DphiDy(i,j) = (1/(12*hy))*(phi(i,j-2)-8*phi(i,j-1)+8*phi(i,j+1)-phi(i,j+2))...
                -psiWENO((phi(i,j-1)-2*phi(i,j-2)+phi(i,j-3))/hy,...
                (phi(i,j)-2*phi(i,j-1)+phi(i,j-2))/hy,...
                (phi(i,j+1)-2*phi(i,j)+phi(i,j-1))/hy,...
                (phi(i,j+2)-2*phi(i,j+1)+phi(i,j))/hy);
        elseif vCell(i,j)<0
            DphiDy(i,j) = (1/(12*hy))*(phi(i,j-2)-8*phi(i,j-1)+8*phi(i,j+1)-phi(i,j+2))...
                +psiWENO((phi(i,j+3)-2*phi(i,j+2)+phi(i,j+1))/hy,...
                (phi(i,j+2)-2*phi(i,j+1)+phi(i,j))/hy,...
                (phi(i,j+1)-2*phi(i,j)+phi(i,j-1))/hy,...
                (phi(i,j)-2*phi(i,j-1)+phi(i,j-2))/hy);
        end
    end
end

end