function [DphiDx,DphiDy] = WENO5_2D(phi,uij,vij,i,j,hx,hy)
if uij>=0
    DphiDx = (1/(12*hx))*(phi(i-2,j)-8*phi(i-1,j)+8*phi(i+1,j)-phi(i+2,j))...
        -psiWENO((phi(i-1,j)-2*phi(i-2,j)+phi(i-3,j))/hx,...
        (phi(i,j)-2*phi(i-1,j)+phi(i-2,j))/hx,...
        (phi(i+1,j)-2*phi(i,j)+phi(i-1,j))/hx,...
        (phi(i+2,j)-2*phi(i+1,j)+phi(i,j))/hx);
elseif uij<0
    DphiDx = (1/(12*hx))*(phi(i-2,j)-8*phi(i-1,j)+8*phi(i+1,j)-phi(i+2,j))...
        +psiWENO((phi(i+3,j)-2*phi(i+2,j)+phi(i+1,j))/hx,...
        (phi(i+2,j)-2*phi(i+1,j)+phi(i,j))/hx,...
        (phi(i+1,j)-2*phi(i,j)+phi(i-1,j))/hx,...
        (phi(i,j)-2*phi(i-1,j)+phi(i-2,j))/hx);
end
if vij>=0
    DphiDy = (1/(12*hy))*(phi(i,j-2)-8*phi(i,j-1)+8*phi(i,j+1)-phi(i,j+2))...
        -psiWENO((phi(i,j-1)-2*phi(i,j-2)+phi(i,j-3))/hy,...
        (phi(i,j)-2*phi(i,j-1)+phi(i,j-2))/hy,...
        (phi(i,j+1)-2*phi(i,j)+phi(i,j-1))/hy,...
        (phi(i,j+2)-2*phi(i,j+1)+phi(i,j))/hy);
elseif vij<0
    DphiDy = (1/(12*hy))*(phi(i,j-2)-8*phi(i,j-1)+8*phi(i,j+1)-phi(i,j+2))...
        +psiWENO((phi(i,j+3)-2*phi(i,j+2)+phi(i,j+1))/hy,...
        (phi(i,j+2)-2*phi(i,j+1)+phi(i,j))/hy,...
        (phi(i,j+1)-2*phi(i,j)+phi(i,j-1))/hy,...
        (phi(i,j)-2*phi(i,j-1)+phi(i,j-2))/hy);
end

end